import keyMirror from 'key-mirror';

export default keyMirror({
  ON_CHANGE_MAP_PAGE_NO: null,
  ON_CHANGE_LIST_SCROLL_POS: null,
  ON_RESET_LIST_ADS: null,
  ON_CHANGE_LIST_ADS: null,
  ON_ALERT_US_CHANGE: null,
  ON_POLYGONS_CHANGE: null,
  ON_DRAW_MODE_CHANGE: null,

  ON_SEARCH_FIELD_CHANGE : null,
  SEARCH_STATE_INPUT: null,
  SEARCH_STATE_LOADING: null,
  SEARCH_STATE_SUCCESS: null,
  SEARCH_STATE_FAILURE: null,
  CHANGE_LOADING_SEARCH_RESULT:null,

  FETCH_DETAIL_FAIL: null,
  FETCH_DETAIL_SUCCESS: null,
  SET_LOADING_DETAIL: null,

  SET_SEARCH_LOAI_TIN : null,


  SET_PLATFORM: null,
  SET_VERSION: null,


  ON_LOGIN_STATE_CHANGE: null,
  LOGIN_STATE_LOGOUT: null,
  LOGIN_STATE_REGISTER: null,
  LOGIN_STATE_LOGIN: null,
  LOGIN_STATE_FORGOT_PASSWORD: null,

  SIGNUP_REQUEST: null,
  SIGNUP_SUCCESS: null,
  SIGNUP_FAILURE: null,

  LOGIN_REQUEST: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,

  LOGOUT_REQUEST: null,
  LOGOUT_SUCCESS: null,
  LOGOUT_FAILURE: null,


  //global
  SET_STATE: null,
  GET_STATE: null,
  SET_STORE: null,

  //search-search result
  SET_LISTRESULT_DATASOURCE:null,
  CHANGE_LISTRESULT_TO_LOADING:null,
  FETCH_SEARCH_RESULT_FAIL: null,
  FETCH_SEARCH_RESULT_SUCCESS : null,
  CHANGE_HOME_REFRESHING: null,
  
  //search - map


  ON_AUTH_FIELD_CHANGE: null,

  LAUNCH_APP:null, //enter application
  ROUTER_FOCUS:null,

  //register
  ON_REGISTER_FIELD_CHANGE:null,
  REGISTER_SUCCESS : null,

  ON_DB_CHANGE: null,

  ON_INBOX_FIELD_CHANGE: null,
  ON_CHAT_FIELD_CHANGE: null,
  REQUEST_START_CHAT : null,
  INSERT_MY_CHAT: null,
  REGISTER_PUSHTOKEN_SUCCESS: null,

  //post ads
  ON_POST_ADS_FIELD_CHANGE:null,
  ON_UPLOAD_IMAGE: null,
  POST_ADS_REQUEST: null,
  POST_ADS_SUCCESS: null,
  POST_ADS_FAILURE: null,
  POST_ADS_GET_DIACHINH_REQUEST: null,
  POST_ADS_GET_DIACHINH_SUCCESS: null,
  POST_ADS_GET_DIACHINH_FAILURE: null,
  
  SEARCH_LIST_LIKE_SUCCESS: null,
  SEARCH_LIST_UNLIKE_SUCCESS: null,
  ON_ADSMGMT_FIELD_CHANGE: null,
  ON_ME_FIELD_CHANGE : null,
  ON_PROFILE_FIELD_CHANGE: null,
  ON_LOADING_PROFILE_REQUEST: null,
  ON_LOADING_PROFILE_SUCCESS: null,
  ON_LOADING_PROFILE_FAILURE: null,
  ON_UPDATING_PROFILE_REQUEST: null,
  ON_UPDATING_PROFILE_SUCCESS: null,
  ON_UPDATING_PROFILE_FAILURE: null,
  ON_UPDATING_PASSWORD_REQUEST: null,
  ON_UPDATING_PASSWORD_SUCCESS: null,
  ON_UPDATING_PASSWORD_FAILURE: null,
  SEARCH_LOAD_SAVED_SEARCH: null,
  CHANGE_LOADING_HOME_DATA : null,
  LOAD_HOME_DATA_DONE : null,
  CHANGE_SEARCH_CALLED_FROM : null,
  ON_SELECTED_PACKAGE_FIELD_CHANGE : null,
  CHANGE_SELECTED_PACKAGE: null,
  CHANGE_PACKAGE_FIELD: null,
  ON_TOPUP_SCRATCH_FIELD_CHANGE: null,

  SAVED_SEARCH_SUCCESS: null,
  SAVED_SEARCH_FAIL: null,
  LOAD_LAST_SEARCH_SUCCESS: null,

  ON_CURRENT_USER_FIELD_CHANGE: null,

  GET_UPDATE_ADS_REQUEST: null,
  GET_UPDATE_ADS_SUCCESS: null,
  GET_UPDATE_ADS_FAILURE: null
});
